name: Conventional CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  conventional-ci:
    uses: rayxiom/workflows/.github/workflows/conventional-ci.yml@v1
    with:
      test: pnpm run test:all
      build-for-test: false
