name: Release Commit to pkg.pr.new

on: [push, pull_request]

jobs:
  release-commit:
    uses: rayxiom/workflows/.github/workflows/release-commit.yml@v1
    with:
      packages: "./packages/*"
      compact: true
